### ISSUE TITLE
DNS Resolution Issues

### ISSUE THREAD

**Issue by derks** [rackerlabs/boot.rackspace.com#19]
Seems like the iPXE environment is having issues resolving DNS.  Trying to chain load off of and external server, and the DNS is failing to resolve 9/10 times.  Don't see any issues outside of that environment:

**Comment by derks** [comment]
I just worked around it by changing the DNS server:

```
iPXE> set dns 8.8.8.8
```


Definitely seems like one of the caching nameservers in that environment is dead tho.

**Comment by amesserl** [comment]
@derks Were you having issues in the Cloud Servers environment in a particular region?  We can go trace that down if needed.  If your testing in your own environment, DNS is just populated by whatever is in DHCP.

**Comment by derks** [comment]
ORD

**Comment by amesserl** [comment]
Was not able to reproduce issue, so assuming caching nameserver is working.  If not, might be a good idea to open up a support ticket.
