### ISSUE TITLE
Broken links to wiki

### ISSUE THREAD

**Issue by pmahoney** [rackerlabs/boot.rackspace.com#20]
This link from the README:

https://github.com/rackerlabs/boot.rackspace.com/wiki/boot.rackspace.com-Image-UUIDs

simply redirects back to the project summary page.

**Comment by amesserl** [comment]
Thanks for finding that.  I'm actually in the process of revamping docs and putting them in mkdocs format.  The page you're looking for is now here:

http://bootrackspacecom.readthedocs.org/en/latest/image_uuids/

Thanks!
