### ISSUE TITLE
CentOS7.0 non booting

### ISSUE THREAD

**Issue by aaronmehar** [rackerlabs/boot.rackspace.com#26]
Hi!
CentOS 7.0 is not booting on iPXE, if this intended with 7.1 working OK? Can it be removed from the menus?

![screen shot 2015-11-02 at 11 29 16 am](https://cloud.githubusercontent.com/assets/8697411/10878876/809cf9e2-8148-11e5-95a8-dc73933deca8.png)

**Comment by antonym** [comment]
It should work now, they deprecated the old numbering scheme which changed some of the directories around (http://mirror.rackspace.com/CentOS/7.0.1406/readme) so I had to make some version tweaks.  Thanks for letting me know.
