### ISSUE TITLE
USB not booting

### ISSUE THREAD

**Issue by MayhemBill** [rackerlabs/boot.rackspace.com#32]
I've created a USB key using DD as mentioned on your wiki. 
For some reason it doesn't boot at all. It just skips right over it. 
Yes I have made sure I am booting from the correct device. 
I'm using this on an HP laptop.

I may not be using it correctly, but I would like to be able to test this service so I may attempt to make my own at home.

**Comment by ghost** [comment]
Some boxes can be picky about iPXE, but in general it should just boot. Does it have a boot sector written to it? 0xAA55 at bytes 510, 511 with byte 0 being the first byte?

I usually check this with `head -c 512 | hexdump -C` and look at the last two bytes.

May want to try another iPXE USB image and see if that works.

**Comment by antonym** [comment]
I'd suggest checking out https://netboot.xyz as I've been putting my effort there these days and it's usually running the latest version of iPXE.  I've ran across issues where some USB keys either won't boot or the USB port isn't seen as a boot device.  If you've run through all the steps to DD the image, I'd suggest trying another USB key or another port.

https://netboot.xyz/boot-usb/

**Comment by MayhemBill** [comment]
I know this is late, but I figured it out, I had wrote the image incorrectly. I had fixed it.
